version: '3.8'
services:
  server:
    build:
      context: .
    container_name: tawasalna-file-manager
    image: ipactconsult/tawasalna-file-manager:${IMAGE_TAG}
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - public:/usr/src/app/public
    restart: unless-stopped

volumes:
  public:
